version: '2'
services:
  users-service:
    image: amrutarajiv/users_service
    container_name: users_service
    ports:
     - "8123:8123"
    links:
      - db:db
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
  db:
    image: amrutarajiv/test_database
