version: '3'
services:
  users-service:
    build: users-service
    environment:
     - DATABASE_HOST=db
    depends_on:
     - db
    ports:
     - "8123:8123"    
    
  db:
    image: amrutarajiv/test_database
