node {
    
    stage('SCM Checkout') {
        git credentialsId: 'github', url: 'https://github.com/amrutarajiv/Node-Docker-Microservice-Demo-Application/tree/master/test-database'
    }

    stage('Build Docker image'){
        bat "docker build -t amrutarajiv/test_database:${env.BUILD_ID} ."
    }

    stage('Push Docker image'){
        withCredentials([string(credentialsId: 'docker-pwd', variable: 'dockerHubPwd')]) {
            bat "docker login -u amrutarajiv -p ${dockerHubPwd}"
        }        
        
        bat "docker push amrutarajiv/test_database:${env.BUILD_ID}"
        
    }

}